"""Turn a song into a zoomasm session: beat-synced zoom + audio-reactive colour.

Part of the Fraktaler 3 + zoomasm workflow (see README): Fraktaler 3
computes exponential-map keyframes once per coordinate, and this script
builds everything zoomasm needs to assemble a music video from them.
Reuses ``mandel_audio``'s music analysis, then writes into ``--out``:

- ``soundtrack.wav``: zoomasm only reads WAV/FLAC.
- ``reactive.glsl``: colour shader. zoomasm has no audio reactivity of
  its own, but shaders can read the current time (``getTime()``), so the
  per-frame bass/mid/treble/loudness are baked in as a lookup table.
- ``session.toml``: zoomasm session with one Linear timeline waypoint per
  video frame, following the same ramp + beat punches as
  ``mandel-audio video``. Playback is muted: zoomasm's realtime player
  glitches audibly when rendering can't keep up, and muting doesn't
  affect the soundtrack muxed into the output video.

Zoom units: zoomasm's timeline Z counts keyframes (0 = deepest keyframe,
+1 = zoom out 2x), the same log2 step as ``mandel_audio``'s ``scale``, so
Z = z_at_scale0 - scale. For keyframes rendered from
``keyframes.f3.toml.template`` (deepest zoom 4e9, where Fraktaler's zoom
Z shows a vertical span of 4/Z and our scale s shows 2.5/2**s),
z_at_scale0 = log2(4e9 / 1.6) ~= 31.22. That calibration is worked out
on paper, not yet checked against rendered frames.

Example::

    python tools/song_to_zoomasm.py --audio song.mp3 --keyframes kf/ \\
        --out session/ --z-at-scale0 31.22 --end-scale 28 -o zoom.mp4
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

import imageio_ffmpeg
import numpy as np
from matplotlib import colormaps

from mandel_audio.audio_analysis import analyze_file
from mandel_audio.reactive import BAND_CMAPS, zoom_schedule

PALETTE_SAMPLES = 32

SHADER_TEMPLATE = """// generated by tools/song_to_zoomasm.py
const int FEAT_N = {feat_n};
const float FEAT_HZ = {feat_hz};
const vec4 FEAT[FEAT_N] = vec4[FEAT_N](
{feat});
const int PAL_N = {pal_n};
const vec3 PAL_BASS[PAL_N] = vec3[PAL_N](
{pal_bass});
const vec3 PAL_MID[PAL_N] = vec3[PAL_N](
{pal_mid});
const vec3 PAL_TREBLE[PAL_N] = vec3[PAL_N](
{pal_treble});

vec4 features(float t)
{{
  float x = clamp(t * FEAT_HZ, 0.0, float(FEAT_N - 1));
  int i = int(floor(x));
  int j = min(i + 1, FEAT_N - 1);
  return mix(FEAT[i], FEAT[j], fract(x));
}}

vec3 samplePal(const vec3 P[PAL_N], float t)
{{
  float x = clamp(t, 0.0, 1.0) * float(PAL_N - 1);
  int i = int(floor(x));
  int j = min(i + 1, PAL_N - 1);
  return mix(P[i], P[j], fract(x));
}}

vec3 colour(void)
{{
  if (getInterior()) return vec3(0.0);
  if (getGlitch()) return vec3(0.0);
  vec4 f = features(getTime());
  vec3 w = f.xyz;
  float s = w.x + w.y + w.z;
  w = s > 0.0 ? w / s : vec3(1.0 / 3.0);
  // smooth, non-wrapping palette index from log iteration count
  float n = log(max(to_float(getN()), 1.0));
  float t = 0.5 - 0.5 * cos(n * 1.7);
  vec3 c = w.x * samplePal(PAL_BASS, t) + w.y * samplePal(PAL_MID, t)
         + w.z * samplePal(PAL_TREBLE, t);
  // distance-estimate edge shading keeps filament detail crisp
  float de = length(getDE());
  c *= clamp(0.35 + 0.65 * tanh(4.0 * de), 0.0, 1.0);
  c *= {min_brightness:.3f} + {brightness_range:.3f} * f.w;
  return pow(c, vec3(2.2)); // sRGB palette -> linear light
}}
"""

SESSION_TEMPLATE = """[audio]
type = "soundtrack"
path = "{wav}"
time = 0.0
speed = 1.0
volume = 0.0
mute = true
loop = false
playing = false

[input]
input = "{keyframes}"
vram_override = true
channels = ["N0", "N1", "NF", "DEX", "DEY"]
reverse = false
flip = false
invert = false
layers = 16

[colour]
colour = "{shader}"
watch = false
samples = 1
shutter = 0.0
projection = "2D"
angle = 0.0

[timeline]
{steps}
[output]
ffmpeg = "{ffmpeg}"
width = {size}
height = {size}
fps = {fps:.1f}
advanced = false
twopass = false
pass1 = ""
pass2 = ""
output = "{output}"
overwrite = true
video_crf = 18
audio_kbps = 384.0
"""


def toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\")


def session_path(path: str | Path, windows_prefix: str | None) -> str:
    """Spell ``path`` as the session file should, for Linux or Windows zoomasm.

    With ``windows_prefix`` (e.g. ``\\\\wsl.localhost\\Ubuntu-22.04``), a
    WSL path becomes the UNC path Windows sees it at.
    """
    s = str(Path(path).resolve())
    if windows_prefix:
        s = windows_prefix.rstrip("\\") + s.replace("/", "\\")
    return toml_escape(s)


def palette_glsl(cmap_name: str) -> str:
    colors = colormaps[cmap_name](np.linspace(0, 1, PALETTE_SAMPLES))[:, :3]
    return ",\n".join(f"  vec3({r:.4f},{g:.4f},{b:.4f})" for r, g, b in colors)


def timeline_toml(z: np.ndarray) -> str:
    n = len(z)
    return "\n".join(
        f'[[timeline.timeline]]\nt = {i / (n - 1):.9f}\nZ = {zi:.6f}\ninterpolation = "Linear"\n'
        for i, zi in enumerate(z)
    )


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--audio", required=True, help="music file (anything ffmpeg reads)")
    p.add_argument("--keyframes", required=True, help="Fraktaler 3 zoom-out sequence folder")
    p.add_argument("--out", required=True, help="folder for the wav, shader and session")
    p.add_argument(
        "--z-at-scale0",
        type=float,
        required=True,
        help="timeline Z that corresponds to mandel_audio scale 0 (full view)",
    )
    p.add_argument("--end-scale", type=float, default=28.0, help="final log2 zoom")
    p.add_argument("--beat-punch", type=float, default=0.6, help="extra zoom-in on beats")
    p.add_argument("--fps", type=int, default=24)
    p.add_argument(
        "--lut-hz", type=int, default=12, help="audio feature samples/sec baked into the shader"
    )
    p.add_argument("--size", type=int, default=1080, help="output video is size x size")
    p.add_argument(
        "--min-brightness", type=float, default=0.4, help="brightness at silence (1.0 at peak)"
    )
    p.add_argument("--max-duration", type=float, default=None, help="cap the video length (s)")
    p.add_argument("-o", "--output", required=True, help="output video path")
    p.add_argument(
        "--windows-prefix",
        default=None,
        help=r"write session paths for Windows zoomasm, e.g. \\wsl.localhost\Ubuntu-22.04",
    )
    p.add_argument(
        "--windows-ffmpeg",
        default=r"C:\ffmpeg\bin\ffmpeg.exe",
        help="ffmpeg.exe path written into the session when --windows-prefix is set",
    )
    a = p.parse_args()

    out = Path(a.out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    ffmpeg = imageio_ffmpeg.get_ffmpeg_exe()

    # 1. soundtrack as WAV
    wav = out / "soundtrack.wav"
    cmd = [ffmpeg, "-v", "error", "-y", "-i", a.audio]
    if a.max_duration:
        cmd += ["-t", str(a.max_duration)]
    subprocess.run([*cmd, "-ar", "48000", "-ac", "2", str(wav)], check=True)

    # 2. zoom path from beats (same schedule as `mandel-audio video`)
    feat = analyze_file(str(wav), fps=a.fps)
    z = a.z_at_scale0 - zoom_schedule(feat, 0.0, a.end_scale, a.beat_punch)

    # 3. colour shader with the audio features baked in
    lut = analyze_file(str(wav), fps=a.lut_hz)
    rows = np.stack([lut.bass, lut.mid, lut.treble, lut.loudness], axis=1)
    shader = out / "reactive.glsl"
    shader.write_text(
        SHADER_TEMPLATE.format(
            feat_n=len(rows),
            feat_hz=float(a.lut_hz),
            feat=",\n".join("  vec4({:.3f},{:.3f},{:.3f},{:.3f})".format(*r) for r in rows),
            pal_n=PALETTE_SAMPLES,
            pal_bass=palette_glsl(BAND_CMAPS["bass"]),
            pal_mid=palette_glsl(BAND_CMAPS["mid"]),
            pal_treble=palette_glsl(BAND_CMAPS["treble"]),
            min_brightness=a.min_brightness,
            brightness_range=1.0 - a.min_brightness,
        )
    )

    # 4. session
    wp = a.windows_prefix
    session = out / "session.toml"
    session.write_text(
        SESSION_TEMPLATE.format(
            wav=session_path(wav, wp),
            keyframes=session_path(a.keyframes, wp),
            shader=session_path(shader, wp),
            steps=timeline_toml(z),
            ffmpeg=toml_escape(a.windows_ffmpeg if wp else ffmpeg),
            size=a.size,
            fps=float(a.fps),
            output=session_path(a.output, wp),
        )
    )
    print(
        f"frames={len(z)} tempo={feat.tempo:.1f} Z: {z.max():.2f} -> {z.min():.2f} "
        f"lut={len(rows)} rows"
    )
    print(session)


if __name__ == "__main__":
    main()
